import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          А вдруг СМА?
        </h2>

        <p className={styles.description}>
          Выберите, кто Ваш пациент:
        </p>

        <div className={styles.grid}>
          
          <div className={styles.card}>
            <h4>Взрослый</h4>
            <Image src="/woman.png" alt="Vercel Logo" width={300} height={300} />
            <div className={styles.comments}>
              <p>Менее тяжелые формы СМА могут возникать и диагностироваться в зрелом возрасте. </p>
            </div>
            <div className={styles.comments}>
            <p>По сравнению с СМА у детей, СМА у взрослых может иметь более легкие симптомы, но без патогенетической терапии пациенты со СМА 2-3 типа неуклонно теряют двигательные навыки. </p>
            </div>
            <div className={styles.comments}>
              <p>По сравнению с СМА в детстве, течение СМА у взрослых может быть более коварным и трудным для распознавания.  </p>
            </div>
          </div>

          <div className={styles.card}>
            <h4>Ребенок</h4>
            <Image src="/child.png" alt="Vercel Logo" width={300} height={300} />
            <div className={styles.comments}>
              <p>Ребенок, плохо удерживающий голову, когда ему придают сидячее положение, с вялыми движениями нижних конечностей или с трудом тянущийся к предметам, но при этом с осмысленным и ярким взглядом, улыбающийся и социально активный, вызывает настороженность в отношении наличия СМА.</p>
            </div>
            <div className={styles.comments}>
              <p>Младенцам со СМА необходимо экстренное направление к специалисту, ранняя диагностика и обеспечение терапией, спасающей жизнь, поскольку эти мотонейроны очень быстро подвергаются дегенерации при прогрессировании заболевания</p>
            </div>
          </div>

          {/* <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
        <p className={styles.description}>Сообщает ли один из ваших пациентов о следующих симптомах? (нажмите на любую иконку и узнайте больше)</p>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}

      
    </div>
  )
}

export default Home
