import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          А вдруг СМА?
        </h2>

        <p className={styles.description}>
          Выберите, кто Ваш пациент:
        </p>

        <div className={styles.grid}>
          
          <div className={styles.card}>
            <h4>Взрослый</h4>
            <Image src="/woman.png" alt="Vercel Logo" width={300} height={300} />
            <div className={styles.comments}>
              <p>Менее тяжелые формы СМА могут возникать и диагностироваться в зрелом возрасте. </p>
            </div>
            <div className={styles.comments}>
            <p>По сравнению с СМА у детей, СМА у взрослых может иметь более легкие симптомы, но без патогенетической терапии пациенты со СМА 2-3 типа неуклонно теряют двигательные навыки. </p>
            </div>
            <div className={styles.comments}>
              <p>По сравнению с СМА в детстве, течение СМА у взрослых может быть более коварным и трудным для распознавания.  </p>
            </div>
          </div>

          <div className={styles.card}>
            <h4>Ребенок</h4>
            <Image src="/child.png" alt="Vercel Logo" width={300} height={300} />
            <div className={styles.comments}>
              <p>Ребенок, плохо удерживающий голову, когда ему придают сидячее положение, с вялыми движениями нижних конечностей или с трудом тянущийся к предметам, но при этом с осмысленным и ярким взглядом, улыбающийся и социально активный, вызывает настороженность в отношении наличия СМА.</p>
            </div>
            <div className={styles.comments}>
              <p>Младенцам со СМА необходимо экстренное направление к специалисту, ранняя диагностика и обеспечение терапией, спасающей жизнь, поскольку эти мотонейроны очень быстро подвергаются дегенерации при прогрессировании заболевания</p>
            </div>
          </div>
        </div>
        <p className={styles.description}>Сообщает ли один из ваших пациентов о следующих симптомах? <a className={styles.link} href='#'>(нажмите на любую иконку и узнайте больше)</a></p>
        

        <div className={styles.wrap}>
          <div className={styles.slider}>

          <div className={styles.circles}>
            <div className={styles.img}>
              <Image src="/pic1.png" alt="pic1" width={135} height={131} />
            </div>
            <p className={styles.innerText}>Утомляемость</p>
          </div>
          
          <div className={styles.circles}>
            <div className={styles.img}>
              <Image src="/pic2.png" alt="pic2" width={135} height={131} />
            </div>
            <p className={styles.innerText}>Сколиоз</p>
          </div>
          
          <div className={styles.circles}>
            <div className={styles.img}>
              <Image src="/pic3.png" alt="pic3" width={135} height={131} />
            </div>
            <p className={styles.innerText}>Ограниченная способность поднимать руки и переносить предметы</p>
          </div>
          
          <div className={styles.circles}>
            <div className={styles.img}>
              <Image src="/pic4.png" alt="pic4" width={135} height={131} />
            </div>
            <p className={styles.innerText}>Вывих бедра</p>
          </div>
          
          <div className={styles.Pic}>
            <Image src="/woman-big.png" alt="woman" width={315} height={315} />
            <p className={styles.innerTextBig}>Взрослый</p>
          </div>

          <div className={styles.circles}>
            <div className={styles.img}>
              <Image src="/pic5.png" alt="pic5" width={135} height={131} />
            </div>
            <p className={styles.innerText}>Нарушения жевания и глотания</p>
          </div>

          <div className={styles.circles}>
            <div className={styles.img}>
              <Image src="/pic6.png" alt="pic6" width={135} height={131} />
            </div>
            <p className={styles.innerText}>Контрактура суставов</p>
          </div>

          <div className={styles.circles}>
            <div className={styles.img}>
              <Image src="/pic7.png" alt="pic7" width={135} height={131} />
            </div>
            <p className={styles.innerText}>Неспособность бегать, изменение походки</p>
          </div>

          <div className={styles.circles}>
            <div className={styles.img}>
              <Image src="/pic8.png" alt="pic8" width={135} height={131} />
            </div>
            <p className={styles.innerText}>Дыхательная недостаточность/ респираторная дисфункция</p>
          </div>
          
          </div>
        </div>
      </main>

    </div>
  )
}

export default Home
